### ISSUE TITLE
Get / Set Project Avatars / Logos

### ISSUE THREAD

**Issue by Sebi94nbg** [rjvandoesburg/laravel-jira-rest-client#19]
Is it possible with this Rest API to get and set project avatars (logos)?

My web application synchronizes projects with Jira in both directions.

Due to this, I need to be able to sync existing projects to my web application and new projects from my web application should be synced to Jira (incl. an project avatar / logo which was uploaded to my web application by a user).

When I get the details of a single project, this includes the avatar URLs for multiple icon sizes, but when I try to get this image using `file_get_contents()` I always get a 403 forbidden error.

**Comment by rjvandoesburg** [comment]
Hey,

At this point it is not possible to update the project Avatar.
I once was working on this but this required a certain way of auth (server & v2) so I have not picked it up yet.

As for the `403` this is happening because the avatars are on the `/secure` group for which you need to be logged in.
You can test this by visiting an avatar in the browser when you are logged in on another tab (you can view the avatar) and opening a private window and try to access the url, you will now receive a 403

To solve the 403 you need to pass authorization of a user who can access those images.
It might be possible to update your permissions on the Jira instance to allow anonymous access to your project avatars, but you would need to look into that.

Cheers,

**Comment by Sebi94nbg** [comment]
Thanks for your quick feedback!

I believe it's not a good solution to allow anonymous access on those images since you can easily get those by "brut-forcing" those URLs with different IDs.

In this case, it's not supported yet. So we need to get / set those avatars manually for now.

I'll close this issue for now. Feel free to reopen it, if you want it as "todo" ticket. :)
